export interface Country {
  name: string;
  code: string;
  flag: string;
  label: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "+93", flag: "https://flagcdn.com/w40/af.png", label: "AF" },
  { name: "Albania", code: "+355", flag: "https://flagcdn.com/w40/al.png", label: "AL" },
  { name: "Algeria", code: "+213", flag: "https://flagcdn.com/w40/dz.png", label: "DZ" },
  { name: "Andorra", code: "+376", flag: "https://flagcdn.com/w40/ad.png", label: "AD" },
  { name: "Angola", code: "+244", flag: "https://flagcdn.com/w40/ao.png", label: "AO" },
  { name: "Argentina", code: "+54", flag: "https://flagcdn.com/w40/ar.png", label: "AR" },
  { name: "Armenia", code: "+374", flag: "https://flagcdn.com/w40/am.png", label: "AM" },
  { name: "Australia", code: "+61", flag: "https://flagcdn.com/w40/au.png", label: "AU" },
  { name: "Austria", code: "+43", flag: "https://flagcdn.com/w40/at.png", label: "AT" },
  { name: "Azerbaijan", code: "+994", flag: "https://flagcdn.com/w40/az.png", label: "AZ" },
  { name: "Bahamas", code: "+1", flag: "https://flagcdn.com/w40/bs.png", label: "BS" },
  { name: "Bahrain", code: "+973", flag: "https://flagcdn.com/w40/bh.png", label: "BH" },
  { name: "Bangladesh", code: "+880", flag: "https://flagcdn.com/w40/bd.png", label: "BD" },
  { name: "Barbados", code: "+1", flag: "https://flagcdn.com/w40/bb.png", label: "BB" },
  { name: "Belarus", code: "+375", flag: "https://flagcdn.com/w40/by.png", label: "BY" },
  { name: "Belgium", code: "+32", flag: "https://flagcdn.com/w40/be.png", label: "BE" },
  { name: "Belize", code: "+501", flag: "https://flagcdn.com/w40/bz.png", label: "BZ" },
  { name: "Benin", code: "+229", flag: "https://flagcdn.com/w40/bj.png", label: "BJ" },
  { name: "Bhutan", code: "+975", flag: "https://flagcdn.com/w40/bt.png", label: "BT" },
  { name: "Bolivia", code: "+591", flag: "https://flagcdn.com/w40/bo.png", label: "BO" },
  { name: "Bosnia & Herzegovina", code: "+387", flag: "https://flagcdn.com/w40/ba.png", label: "BA" },
  { name: "Botswana", code: "+267", flag: "https://flagcdn.com/w40/bw.png", label: "BW" },
  { name: "Brazil", code: "+55", flag: "https://flagcdn.com/w40/br.png", label: "BR" },
  { name: "Brunei", code: "+673", flag: "https://flagcdn.com/w40/bn.png", label: "BN" },
  { name: "Bulgaria", code: "+359", flag: "https://flagcdn.com/w40/bg.png", label: "BG" },
  { name: "Burkina Faso", code: "+226", flag: "https://flagcdn.com/w40/bf.png", label: "BF" },
  { name: "Burundi", code: "+257", flag: "https://flagcdn.com/w40/bi.png", label: "BI" },
  { name: "Cambodia", code: "+855", flag: "https://flagcdn.com/w40/kh.png", label: "KH" },
  { name: "Cameroon", code: "+237", flag: "https://flagcdn.com/w40/cm.png", label: "CM" },
  { name: "Canada", code: "+1", flag: "https://flagcdn.com/w40/ca.png", label: "CA" },
  { name: "Chile", code: "+56", flag: "https://flagcdn.com/w40/cl.png", label: "CL" },
  { name: "China", code: "+86", flag: "https://flagcdn.com/w40/cn.png", label: "CN" },
  { name: "Colombia", code: "+57", flag: "https://flagcdn.com/w40/co.png", label: "CO" },
  { name: "Costa Rica", code: "+506", flag: "https://flagcdn.com/w40/cr.png", label: "CR" },
  { name: "Croatia", code: "+385", flag: "https://flagcdn.com/w40/hr.png", label: "HR" },
  { name: "Cuba", code: "+53", flag: "https://flagcdn.com/w40/cu.png", label: "CU" },
  { name: "Cyprus", code: "+357", flag: "https://flagcdn.com/w40/cy.png", label: "CY" },
  { name: "Czech Republic", code: "+420", flag: "https://flagcdn.com/w40/cz.png", label: "CZ" },
  { name: "Denmark", code: "+45", flag: "https://flagcdn.com/w40/dk.png", label: "DK" },
  { name: "Djibouti", code: "+253", flag: "https://flagcdn.com/w40/dj.png", label: "DJ" },
  { name: "Dominican Republic", code: "+1", flag: "https://flagcdn.com/w40/do.png", label: "DO" },
  { name: "Ecuador", code: "+593", flag: "https://flagcdn.com/w40/ec.png", label: "EC" },
  { name: "Egypt", code: "+20", flag: "https://flagcdn.com/w40/eg.png", label: "EG" },
  { name: "El Salvador", code: "+503", flag: "https://flagcdn.com/w40/sv.png", label: "SV" },
  { name: "Estonia", code: "+372", flag: "https://flagcdn.com/w40/ee.png", label: "EE" },
  { name: "Ethiopia", code: "+251", flag: "https://flagcdn.com/w40/et.png", label: "ET" },
  { name: "Fiji", code: "+679", flag: "https://flagcdn.com/w40/fj.png", label: "FJ" },
  { name: "Finland", code: "+358", flag: "https://flagcdn.com/w40/fi.png", label: "FI" },
  { name: "France", code: "+33", flag: "https://flagcdn.com/w40/fr.png", label: "FR" },
  { name: "Georgia", code: "+995", flag: "https://flagcdn.com/w40/ge.png", label: "GE" },
  { name: "Germany", code: "+49", flag: "https://flagcdn.com/w40/de.png", label: "DE" },
  { name: "Ghana", code: "+233", flag: "https://flagcdn.com/w40/gh.png", label: "GH" },
  { name: "Greece", code: "+30", flag: "https://flagcdn.com/w40/gr.png", label: "GR" },
  { name: "Guatemala", code: "+502", flag: "https://flagcdn.com/w40/gt.png", label: "GT" },
  { name: "Guyana", code: "+592", flag: "https://flagcdn.com/w40/gy.png", label: "GY" },
  { name: "Haiti", code: "+509", flag: "https://flagcdn.com/w40/ht.png", label: "HT" },
  { name: "Honduras", code: "+504", flag: "https://flagcdn.com/w40/hn.png", label: "HN" },
  { name: "Hong Kong", code: "+852", flag: "https://flagcdn.com/w40/hk.png", label: "HK" },
  { name: "Hungary", code: "+36", flag: "https://flagcdn.com/w40/hu.png", label: "HU" },
  { name: "Iceland", code: "+354", flag: "https://flagcdn.com/w40/is.png", label: "IS" },
  { name: "India", code: "+91", flag: "https://flagcdn.com/w40/in.png", label: "IN" },
  { name: "Indonesia", code: "+62", flag: "https://flagcdn.com/w40/id.png", label: "ID" },
  { name: "Iran", code: "+98", flag: "https://flagcdn.com/w40/ir.png", label: "IR" },
  { name: "Iraq", code: "+964", flag: "https://flagcdn.com/w40/iq.png", label: "IQ" },
  { name: "Ireland", code: "+353", flag: "https://flagcdn.com/w40/ie.png", label: "IE" },
  { name: "Israel", code: "+972", flag: "https://flagcdn.com/w40/il.png", label: "IL" },
  { name: "Italy", code: "+39", flag: "https://flagcdn.com/w40/it.png", label: "IT" },
  { name: "Jamaica", code: "+1", flag: "https://flagcdn.com/w40/jm.png", label: "JM" },
  { name: "Japan", code: "+81", flag: "https://flagcdn.com/w40/jp.png", label: "JP" },
  { name: "Jordan", code: "+962", flag: "https://flagcdn.com/w40/jo.png", label: "JO" },
  { name: "Kazakhstan", code: "+7", flag: "https://flagcdn.com/w40/kz.png", label: "KZ" },
  { name: "Kenya", code: "+254", flag: "https://flagcdn.com/w40/ke.png", label: "KE" },
  { name: "Kuwait", code: "+965", flag: "https://flagcdn.com/w40/kw.png", label: "KW" },
  { name: "Kyrgyzstan", code: "+996", flag: "https://flagcdn.com/w40/kg.png", label: "KG" },
  { name: "Laos", code: "+856", flag: "https://flagcdn.com/w40/la.png", label: "LA" },
  { name: "Latvia", code: "+371", flag: "https://flagcdn.com/w40/lv.png", label: "LV" },
  { name: "Lebanon", code: "+961", flag: "https://flagcdn.com/w40/lb.png", label: "LB" },
  { name: "Libya", code: "+218", flag: "https://flagcdn.com/w40/ly.png", label: "LY" },
  { name: "Liechtenstein", code: "+423", flag: "https://flagcdn.com/w40/li.png", label: "LI" },
  { name: "Lithuania", code: "+370", flag: "https://flagcdn.com/w40/lt.png", label: "LT" },
  { name: "Luxembourg", code: "+352", flag: "https://flagcdn.com/w40/lu.png", label: "LU" },
  { name: "Macau", code: "+853", flag: "https://flagcdn.com/w40/mo.png", label: "MO" },
  { name: "Macedonia", code: "+389", flag: "https://flagcdn.com/w40/mk.png", label: "MK" },
  { name: "Madagascar", code: "+261", flag: "https://flagcdn.com/w40/mg.png", label: "MG" },
  { name: "Malawi", code: "+265", flag: "https://flagcdn.com/w40/mw.png", label: "MW" },
  { name: "Malaysia", code: "+60", flag: "https://flagcdn.com/w40/my.png", label: "MY" },
  { name: "Maldives", code: "+960", flag: "https://flagcdn.com/w40/mv.png", label: "MV" },
  { name: "Mali", code: "+223", flag: "https://flagcdn.com/w40/ml.png", label: "ML" },
  { name: "Malta", code: "+356", flag: "https://flagcdn.com/w40/mt.png", label: "MT" },
  { name: "Mauritius", code: "+230", flag: "https://flagcdn.com/w40/mu.png", label: "MU" },
  { name: "Mexico", code: "+52", flag: "https://flagcdn.com/w40/mx.png", label: "MX" },
  { name: "Moldova", code: "+373", flag: "https://flagcdn.com/w40/md.png", label: "MD" },
  { name: "Monaco", code: "+377", flag: "https://flagcdn.com/w40/mc.png", label: "MC" },
  { name: "Mongolia", code: "+976", flag: "https://flagcdn.com/w40/mn.png", label: "MN" },
  { name: "Montenegro", code: "+382", flag: "https://flagcdn.com/w40/me.png", label: "ME" },
  { name: "Morocco", code: "+212", flag: "https://flagcdn.com/w40/ma.png", label: "MA" },
  { name: "Mozambique", code: "+258", flag: "https://flagcdn.com/w40/mz.png", label: "MZ" },
  { name: "Myanmar", code: "+95", flag: "https://flagcdn.com/w40/mm.png", label: "MM" },
  { name: "Namibia", code: "+264", flag: "https://flagcdn.com/w40/na.png", label: "NA" },
  { name: "Nepal", code: "+977", flag: "https://flagcdn.com/w40/np.png", label: "NP" },
  { name: "Netherlands", code: "+31", flag: "https://flagcdn.com/w40/nl.png", label: "NL" },
  { name: "New Zealand", code: "+64", flag: "https://flagcdn.com/w40/nz.png", label: "NZ" },
  { name: "Nicaragua", code: "+505", flag: "https://flagcdn.com/w40/ni.png", label: "NI" },
  { name: "Niger", code: "+227", flag: "https://flagcdn.com/w40/ne.png", label: "NE" },
  { name: "Nigeria", code: "+234", flag: "https://flagcdn.com/w40/ng.png", label: "NG" },
  { name: "Norway", code: "+47", flag: "https://flagcdn.com/w40/no.png", label: "NO" },
  { name: "Oman", code: "+968", flag: "https://flagcdn.com/w40/om.png", label: "OM" },
  { name: "Pakistan", code: "+92", flag: "https://flagcdn.com/w40/pk.png", label: "PK" },
  { name: "Palestine", code: "+970", flag: "https://flagcdn.com/w40/ps.png", label: "PS" },
  { name: "Panama", code: "+507", flag: "https://flagcdn.com/w40/pa.png", label: "PA" },
  { name: "Paraguay", code: "+595", flag: "https://flagcdn.com/w40/py.png", label: "PY" },
  { name: "Peru", code: "+51", flag: "https://flagcdn.com/w40/pe.png", label: "PE" },
  { name: "Philippines", code: "+63", flag: "https://flagcdn.com/w40/ph.png", label: "PH" },
  { name: "Poland", code: "+48", flag: "https://flagcdn.com/w40/pl.png", label: "PL" },
  { name: "Portugal", code: "+351", flag: "https://flagcdn.com/w40/pt.png", label: "PT" },
  { name: "Qatar", code: "+974", flag: "https://flagcdn.com/w40/qa.png", label: "QA" },
  { name: "Romania", code: "+40", flag: "https://flagcdn.com/w40/ro.png", label: "RO" },
  { name: "Russia", code: "+7", flag: "https://flagcdn.com/w40/ru.png", label: "RU" },
  { name: "Rwanda", code: "+250", flag: "https://flagcdn.com/w40/rw.png", label: "RW" },
  { name: "Saudi Arabia", code: "+966", flag: "https://flagcdn.com/w40/sa.png", label: "SA" },
  { name: "Senegal", code: "+221", flag: "https://flagcdn.com/w40/sn.png", label: "SN" },
  { name: "Serbia", code: "+381", flag: "https://flagcdn.com/w40/rs.png", label: "RS" },
  { name: "Singapore", code: "+65", flag: "https://flagcdn.com/w40/sg.png", label: "SG" },
  { name: "Slovakia", code: "+421", flag: "https://flagcdn.com/w40/sk.png", label: "SK" },
  { name: "Slovenia", code: "+386", flag: "https://flagcdn.com/w40/si.png", label: "SI" },
  { name: "Somalia", code: "+252", flag: "https://flagcdn.com/w40/so.png", label: "SO" },
  { name: "South Africa", code: "+27", flag: "https://flagcdn.com/w40/za.png", label: "ZA" },
  { name: "South Korea", code: "+82", flag: "https://flagcdn.com/w40/kr.png", label: "KR" },
  { name: "Spain", code: "+34", flag: "https://flagcdn.com/w40/es.png", label: "ES" },
  { name: "Sri Lanka", code: "+94", flag: "https://flagcdn.com/w40/lk.png", label: "LK" },
  { name: "Sudan", code: "+249", flag: "https://flagcdn.com/w40/sd.png", label: "SD" },
  { name: "Sweden", code: "+46", flag: "https://flagcdn.com/w40/se.png", label: "SE" },
  { name: "Switzerland", code: "+41", flag: "https://flagcdn.com/w40/ch.png", label: "CH" },
  { name: "Syria", code: "+963", flag: "https://flagcdn.com/w40/sy.png", label: "SY" },
  { name: "Taiwan", code: "+886", flag: "https://flagcdn.com/w40/tw.png", label: "TW" },
  { name: "Tajikistan", code: "+992", flag: "https://flagcdn.com/w40/tj.png", label: "TJ" },
  { name: "Tanzania", code: "+255", flag: "https://flagcdn.com/w40/tz.png", label: "TZ" },
  { name: "Thailand", code: "+66", flag: "https://flagcdn.com/w40/th.png", label: "TH" },
  { name: "Togo", code: "+228", flag: "https://flagcdn.com/w40/tg.png", label: "TG" },
  { name: "Trinidad & Tobago", code: "+1", flag: "https://flagcdn.com/w40/tt.png", label: "TT" },
  { name: "Tunisia", code: "+216", flag: "https://flagcdn.com/w40/tn.png", label: "TN" },
  { name: "Turkey", code: "+90", flag: "https://flagcdn.com/w40/tr.png", label: "TR" },
  { name: "Turkmenistan", code: "+993", flag: "https://flagcdn.com/w40/tm.png", label: "TM" },
  { name: "Uganda", code: "+256", flag: "https://flagcdn.com/w40/ug.png", label: "UG" },
  { name: "Ukraine", code: "+380", flag: "https://flagcdn.com/w40/ua.png", label: "UA" },
  { name: "United Arab Emirates", code: "+971", flag: "https://flagcdn.com/w40/ae.png", label: "AE" },
  { name: "United Kingdom", code: "+44", flag: "https://flagcdn.com/w40/gb.png", label: "UK" },
  { name: "United States", code: "+1", flag: "https://flagcdn.com/w40/us.png", label: "US" },
  { name: "Uruguay", code: "+598", flag: "https://flagcdn.com/w40/uy.png", label: "UY" },
  { name: "Uzbekistan", code: "+998", flag: "https://flagcdn.com/w40/uz.png", label: "UZ" },
  { name: "Venezuela", code: "+58", flag: "https://flagcdn.com/w40/ve.png", label: "VE" },
  { name: "Vietnam", code: "+84", flag: "https://flagcdn.com/w40/vn.png", label: "VN" },
  { name: "Yemen", code: "+967", flag: "https://flagcdn.com/w40/ye.png", label: "YE" },
  { name: "Zambia", code: "+260", flag: "https://flagcdn.com/w40/zm.png", label: "ZM" },
  { name: "Zimbabwe", code: "+263", flag: "https://flagcdn.com/w40/zw.png", label: "ZW" }
];
